### ISSUE TITLE
React-Rails Router Server Sider Rendering

### ISSUE THREAD

**Issue by BunHouth** [pioz/rails_with_react_and_react_router_example#1]
Did you manage to get this work? I also get the same problem.

**Comment by pioz** [comment]
@BunHouth see http://stackoverflow.com/questions/35939324/server-rendering-with-rails-react-rails-gem-react-router

**Comment by BunHouth** [comment]
@pioz  I see it but i don't understand. I can make it work with node js but i can't make it work with react-rails.
I have stuck with this problem for 2 days.

**Comment by BunHouth** [comment]
@pioz I got it work, But URL seem to be not change

**Comment by BunHouth** [comment]
I got it work.
